### ISSUE TITLE
new duolingo tree update broke everything

### ISSUE THREAD

**Issue by film2860** [ToranSharma/Duo-Strength#217]

**Comment by ToranSharma** [comment]
Thanks for reporting. I'm always from a computer for a few days. I'll try to look at this as soon as I can

**Comment by Origitalus** [comment]
I wouldn't say EVERYTHING, but the sentence hiding doesn't work anymore for me.

**Comment by Ajakab98** [comment]
Hey thank you for making Duo Strength, I've been using it for a bit and it's been very useful. The sentence hiding was a great feature, and unfortunately it stopped working for me as well a few days ago.

**Comment by hxhxd** [comment]
Legendary button in tips broke, became practice.  
Those annoying cartoon figures are not hidden anymore.

Hope these get fixed.  
Thanks :)

**Comment by ToranSharma** [comment]
Hi all, just about to push out v2.0.28. I think I have fixed all the things you have mentioned. Here are the fixes to be included in this next version:
### Fixed
- Lesson Detection, which fixes:
  - Cartoon hiding.
  - Sentence hiding.
- Sentence hiding reveal hotkey.
- Skill popout small button styling.
- Tips page Legendary button.
- Page scrolling when page loaded with a skill popout.

**Comment by Ajakab98** [comment]
Thank you very much for fixing the things so quickly! When can we expect v2.0.28 to be live on the Chrome Web Store?

**Comment by hxhxd** [comment]
> Thank you very much for fixing the things so quickly! When can we expect v2.0.28 to be live on the Chrome Web Store?

It's updated now.  

> Hi all, just about to push out v2.0.28 (#218) I think I have fixed all the things you have mentioned. Here are the fixes to be included in this next version:
> 
> ### Fixed
> * Lesson Detection, which fixes:
>   
>   * Cartoon hiding.
>   * Sentence hiding.
> * Sentence hiding reveal hotkey.
> * Skill popout small button styling.
> * Tips page Legendary button.
> * Page scrolling when page loaded with a skill popout.

Hi, thanks for the upgrade.  
The Legendary button seems still not working, it's basically the same as practice button.  
Not a big deal though, I can remove the "practice" tail to make it work.  
Just hope you can fix it when you update it next time :)  
![Screenshot (44)](https://user-images.githubusercontent.com/12712206/187024659-d0537775-1d60-4225-9968-6cc469465cf4.png)
![Screenshot (45)](https://user-images.githubusercontent.com/12712206/187024671-afdb2483-f573-4863-a905-707bafcd9bac.png)

**Comment by ToranSharma** [comment]
@hxhxd,
Thanks for letting me know, I'll have another look at the tips page buttons when I can.

I'll close this issue now.
